### ISSUE TITLE
Cannot precompile with Julia v0.6.3

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGL/GLAbstraction.jl#91] opened 2018-05-31 17:57 UTC
`using GLAbstraction` leads to error
```
julia> using GLAbstraction
INFO: Precompiling module GLAbstraction.
ERROR: LoadError: LoadError: TypeError: UnionAll: expected Type, got Int64
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:576
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\jr\.julia\v0.6\GLAbstraction\src\GLMatrixMath.jl, in expression starting on line 218
while loading C:\Users\jr\.julia\v0.6\GLAbstraction\src\GLAbstraction.jl, in expression starting on line 112
ERROR: Failed to precompile GLAbstraction to C:\Users\jr\.julia\lib\v0.6\GLAbstraction.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
```

`versioninfo()`
```
Julia Version 0.6.3
Commit d55cadc350* (2018-05-28 20:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by jaakkor2** [comment] 2018-05-31 22:20
```
using Quaternions
using GeometryTypes

function (::Type{M})(q::Quaternions.Quaternion) where M <: Mat4
    T = eltype(M)
    sx, sy, sz = 2q.s*q.v1,  2q.s*q.v2,   2q.s*q.v3
    xx, xy, xz = 2q.v1^2,    2q.v1*q.v2,  2q.v1*q.v3
    yy, yz, zz = 2q.v2^2,    2q.v2*q.v3,  2q.v3^2
    T0, T1 = zero(T), one(T)
    Mat{4}(
        T1-(yy+zz), xy+sz,      xz-sy,      T0,
        xy-sz,      T1-(xx+zz), yz+sx,      T0,
        xz+sy,      yz-sx,      T1-(xx+yy), T0,
        T0,         T0,         T0,         T1
    )
end

function (::Type{M})(q::Quaternions.Quaternion) where M <: Mat3
    T = eltype(M)
    sx, sy, sz = 2q.s*q.v1, 2q.s*q.v2,  2q.s*q.v3
    xx, xy, xz = 2q.v1^2,   2q.v1*q.v2, 2q.v1*q.v3
    yy, yz, zz = 2q.v2^2,   2q.v2*q.v3, 2q.v3^2
    T0, T1 = zero(T), one(T)
    Mat{3}(
        T1-(yy+zz), xy+sz,      xz-sy,
        xy-sz,      T1-(xx+zz), yz+sx,
        xz+sy,      yz-sx,      T1-(xx+yy)
    )
end
```
results in
`ERROR: TypeError: UnionAll: expected Type, got Int64`

**Comment by jaakkor2** [comment] 2018-05-31 22:28
```
using GeometryTypes

function (::Type{M})(q) where M <: Mat4
    1
end

function (::Type{M})(q) where M <: Mat3
    2
end
```
results in
`ERROR: TypeError: UnionAll: expected Type, got Int64`
on Julia v0.6.3, but is ok on Julia v0.6.2 .

**Comment by oschulz** [comment] 2018-06-01 07:17
I just ran into the same issue (CentOS-7, Julia v0.6.3, custom build).

**Comment by SimonDanisch** [comment] 2018-06-01 08:55
I opened an issue: https://github.com/JuliaLang/julia/issues/27361

**Comment by oschulz** [comment] 2018-06-02 07:58
Until the Julia issue is fixed, would this do as a workaround?

```julia
function (::Type{Mat4{T}})(q::Quaternions.Quaternion) where T
    # ...
end

function (::Type{Mat3{T}})(q::Quaternions.Quaternion) where T
    # ...
end
```

**Comment by DealPete** [comment] 2018-06-02 14:31
I can't use GLVisualize at all, because when I import it it tries to precompile, and fails on GLAbstraction.

**Comment by SimonDanisch** [comment] 2018-06-04 10:58
If it solves it, feel free to open a PR :)

**Comment by SimonDanisch** [comment] 2018-06-04 10:58
(and thanks for figuring it out!)

**Comment by oschulz** [comment] 2018-06-04 12:27
Question is, do we want to implement a workaround, and do an interim release of GLAbstraction, or hope for a speedy Julia-0.6.4). There seem to be more regressions in 0.6.3 (JuliaLang/julia#27381, JuliaLang/julia#27345), but I have no idea whether there will be a quick bug-fix release or not ...

**Comment by SimonDanisch** [comment] 2018-06-04 12:46
If you have it ready locally & it helps people, I'd be happy to merge & tag!

**Comment by getzze** [comment] 2018-06-11 10:03
Maybe the Rotation.jl package could be used for some functions in GLAbstraction, according to https://github.com/JuliaArrays/StaticArrays.jl/issues/423#issuecomment-394349786
It would reduce code redundancy and bugs.

**Comment by SimonDanisch** [comment] 2018-06-11 10:08
Would be nice! I have never looked a lot into this, since I've had GLMatrixMath, a 270 loc file, since forever and never needed anything more ;) Not sure if Rotations.jl even covers the functionality ...

**Comment by SimonDanisch** [comment] 2018-06-20 07:52
Should be fixed now: JuliaLang/METADATA.jl#15225 I

**Closed by SimonDanisch** 2018-06-20 07:52 UTC

**Comment by oschulz** [comment] 2018-06-20 11:41
@SimonDanisch , thanks! Sorry, I didn't get around to do the PR for you, was a bit overloaded.
